//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Table流浪狗s1091722
    {
        [Required(ErrorMessage ="編號不可空白")]
        public string 編號 { get; set; }
        
        public string 動物別 { get; set; }
        [StringLength(1, ErrorMessage = "性別為公或母")]
        public string 性別 { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> 領養日期 { get; set; }
        public bool 是否打過疫苗 { get; set; }
        [Required(ErrorMessage = "領養人不可空白")]
        public string 領養人 { get; set; }
        [StringLength(10,ErrorMessage ="手機號碼最多為10碼")]
        public string 電話 { get; set; }
        [EmailAddress(ErrorMessage ="格式錯誤")]
        public string 電子郵件 { get; set; }
    }
}
